[workspace]

members = ["scoper-attr",]

[package]
authors = ["Fabian Osyguß <fabian.osyguss@gmail.com>"]
edition = "2024"
name = "scoper"
version = "0.2.0"


[dependencies]
scoper-attr = {path = "scoper-attr"}
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.138"
const_format = "0.2.34"