#https://rust-lang.github.io/rustfmt/?version=v1.6.0
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
max_width = 132
#chain_width = 60
#fn_call_width = 60
fn_single_line = true
match_arm_blocks = false
match_block_trailing_comma = true
reorder_modules = true
combine_control_expr = false
format_strings = true
imports_granularity = "Crate"
reorder_impl_items = true
group_imports = "StdExternalCrate"
#single_line_let_else_max_width = 100
#trailing_comma = "Always"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true