[package]
name = "scoper-attr"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.79", default-features = false, features = ["parsing", "full", "printing"] }
quote = "1.0.37"